// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qomrdcwzwwdcatpvvgax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbXJkY3d6d3dkY2F0cHZ2Z2F4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDEzMjksImV4cCI6MjA2NzM3NzMyOX0.cUJs07-O7Ucs2tnaeVcdCxE1j2ggcJhPoJe8nP3xfJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});